// License: LGPL-3.0-or-later
// this will be generated by some route generator in future but for now, we'll handcode it.

export default {

	new_user_password_path: ():string => {
		return "/users/password/new";
	},

};