/**
 * API title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ValidationError {
    /**
     * Params where the following had an error.
     */
    params?: Array<string>;

    /**
     * The validation messages for the params
     */
    messages?: Array<string>;

}
export class ValidationErrorException implements Error{

    constructor(obj:ValidationError, message?:string){
            this.item = obj;
            this.item = obj;

    }

    message: string;
    stack: string;
    name: string;

    item: ValidationError;
}


