require:
- rubocop-rspec

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  # we do this because I see no gain to being super restrictive
  Max: 5

RSpec/NotToNot:
  Enabled: false

RSpec/SharedExamples: 
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10
