#!/usr/bin/env bash
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ $current_branch == "PRIVATE_PROD_DEPLOY" ]; then
    echo "For safety, you can't run this on the deploy branch"
    exit 1;
fi

docker-compose run web $@
