// License: LGPL-3.0-or-later
// this will be generated by some route generator in future but for now, we'll handcode it.

export default {

	/**
	 * camelcased api_users_current
	 */
	apiUsersCurrent: {
		path: (): string => {
			return "/api/users/current";
		},
		url: (): string => {
			return "/api/users/current";
		},
	},
};