// License: LGPL-3.0-or-later
// this will be generated by some route generator in future but for now, we'll handcode it.

export default {
	nonprofitsSupporters: {
		path: (props: {id:string, sid?:string}):string => {
			const url = new URL(`/nonprofits/${props.id}/supporters`);
			if (props.sid) {
				url.searchParams.set('sid', props.sid);
			}

			return url.toString();
		},

		url: (props: {id:string, sid?:string}):string => {

			const url = new URL(`/nonprofits/${props.id}/supporters`);
			if (props.sid) {
				url.searchParams.set('sid', props.sid);
			}

			return url.toString();
		},

	},
};