name: 'After Checkout Prep'
description: 'prep'
inputs:
  node:
    description: "Which node version?"
  ruby:
    description: "Which node version?"
runs:
  using: "composite"
  steps:
    - name: Setup PostgreSQL with PostgreSQL extensions and unprivileged user
      uses: Daniel-Marynicz/postgresql-action@1.0.0
      with:
        postgres_image_tag: 12-alpine
        postgres_user: houdini_user
        postgres_password: password
    - name: "Install NPM packages"
      uses: "./.github/actions/install-packages"
      if: ${{ inputs.node && inputs.node != '' && inputs.node != 'false' }}
      with:
        node: ${{ inputs.node }}
    - name: "Install Ruby packages"
      uses: "./.github/actions/install-packages"
      if: ${{ inputs.ruby && inputs.ruby != '' && inputs.ruby != 'false' }}
      with:
        ruby: ${{ inputs.ruby }}
    
    