name: 'Checkout and prepare'
description: 'Greet someone'
inputs:
  node-version:
    description: "Which node version?"
  ruby-version:
    description: "Which node version?"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Setup PostgreSQL with PostgreSQL extensions and unprivileged user
      uses: Daniel-Marynicz/postgresql-action@1.0.0
      with:
        postgres_image_tag: 12-alpine
        postgres_user: houdini_user
        postgres_password: password
    - name: "Install packages"
      uses: "./.github/actions/install-packages"
      with:
        node: ${{ inputs.node-version }}
        ruby: ${{ inputs.ruby-version }}
    
    