
module GenerateLocales 

	def self.generate
		I18n::JS::export
		File.open(Rails.root.join('app', 'javascript', 'i18n', 'locales', 'index.js'), 'w') do |file|
			file << "// DO NOT MODIFY THIS FILE. AUTOGENERATED\n"

			file << "const translations = {};\n\n"
			I18n::JS::translations.select{|k,v| Houdini.intl.available_locales.map{|i| i.to_s}.include?(k.to_s)}.keys.each do |k|
				file << "translations['#{k}'] = require('./#{k}.js').default['#{k}'];\n"
			end

			file << "\nexport default translations;"
		end
	end
end