# License: CC0-1.0
general:
  name: CommitChange
  logo: "logos/commitchange_logo_bug.svg"
  logo_full: "logos/commitchange_logo_full.svg"
  poweredby_logo: "logos/commitchange-logo-rectangle-color-150.png"

default:
  image:
    profile: "/images/fallback/default-profile.png"
    nonprofit: "/images/fallback/default-nonprofit.png"
    campaign: "/fallback/default-campaign-background.jpg"


aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-west-1
  bucket_name: commitchange-test-bucket

mailer:
  host: "localhost"
  default_from: "CommitChange Team <support@commitchange.com>"
  email: "support@commitchange.com"

cdn:
  url: "http://localhost:5000"

payment_provider:
  stripe_connect: true
  stripe_public_key: <%= ENV['STRIPE_API_PUBLIC'] %>
  stripe_private_key: <%= ENV['STRIPE_API_KEY'] %>
  stripe_proprietary_v2_js: true

default_bp:
  id: 42
  percentage_fee: 0.030

devise:
  mailer_sender: "support@commitchange.com"

maps:
  provider: "google"
  options:
    key: "<%= ENV['GOOGLE_API_KEY'] %>"

page_editor:
  editor: 'froala'
  editor_options:
    froala_key: <%= ENV['FROALA_KEY'] %>

language: 'en'
available_locales: ['en']
show_state_field: true

intntl:
  currencies: ["usd"]
  all_currencies:
    - unit: "dollars"
      subunit: "cents"
      symbol: "$"
      abbv: "usd"
      format: "%u%n"

source_tokens:
  max_uses: 1
  expiration_time: 1200
  event_donation_source:
    time_after_event: 1728000
    max_uses: 20

nonprofits_must_be_vetted: true

terms_and_privacy:
  help_url: "https://help.commitchange.com"
  privacy_url: "https://commitchange.com/privacy-terms/#privacy_policy"
  terms_url: "https://commitchange.com/privacy-terms/"
  about_url: "https://commitchange.com/us/"


ccs:
  ccs_method: 'github'
  options:
    account: 'CommitChange'
    repo: 'houdini'
    
flat_fee_coverage_percent: 0.05