# License: AGPL-3.0-or-later WITH Web-Template-Output-Additional-Permission-3.0-or-later
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2727a83ceb66f0b4e8437048f4d19a9e8011b04fa4f2b81e862359271ec01cdfa160dce58b3fada9c3c8be28d9b58de9c1bd2c6a91e9b58bdb79ac1ee80e68be

test:
  secret_key_base: 1b36d12444b332c348589061db5bdf1faff86307918dae01f2280b85b157538a671d7c766cfe03838e9ad1869a9fc5f3d0a48e0398297e01017306cc8c53de8c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
