# frozen_string_literal: true

# License: AGPL-3.0-or-later WITH WTO-AP-3.0-or-later
# Full license explanation at https://github.com/houdiniproject/houdini/blob/master/LICENSE
require "bundler/setup"

load "rails/tasks/statistics.rake"

require "bundler/gem_tasks"
