// License: LGPL-3.0-or-later
// this will be generated by some route generator in future but for now, we'll handcode it.
export default {
	/** not correct but good enough for testing */
	root_url: ():string => {
		return "/";
	},
};