// License: LGPL-3.0-or-later
// this will be generated by JSRoutes but for now we'll mock it.
const routes = {
	new_user_password_path: ():string => {
		return "/users/password/new";
	},
	static_terms_and_privacy_path: ():string => {
		return "/static/terms_and_privacy";
	},
};

export default routes;