// License: LGPL-3.0-or-later
// this will be generated by some route generator in future but for now, we'll handcode it.

export default {
	nonprofitsCampaigns: {
		path: (props: {id:string}):string => {
			return `/nonprofits/${props.id}/campaigns`;
		},

		url: (props: {id:string}):string => {
			return `/nonprofits/${props.id}/campaigns`;
		},

	},

	nameAndIdNonprofitCampaigns: {
		path: (props: {id:string}):string => {
			return `/nonprofits/${props.id}/campaigns/name_and_id`;
		},

		url: (props: {id:string}):string => {
			return `/nonprofits/${props.id}/campaigns/name_and_id`;
		},
	},
};