// License: LGPL-3.0-or-later
// this will be generated by some route generator in future but for now, we'll handcode it.

export default {
	nonprofitsEvents: {
		path: (props: { id: string }): string => {
			return `/nonprofits/${props.id}/events`;
		},

		url: (props: { id: string }): string => {
			return `/nonprofits/${props.id}/events`;
		},

	},

	nameAndIdNonprofitEvents: {
		path: (props: {id:string}):string => {
			return `/nonprofits/${props.id}/events/name_and_id`;
		},

		url: (props: {id:string}):string => {
			return `/nonprofits/${props.id}/events/name_and_id`;
		},
	},
};