# frozen_string_literal: true

# License: AGPL-3.0-or-later WITH WTO-AP-3.0-or-later
# Full license explanation at https://github.com/houdiniproject/houdini/blob/main/LICENSE

module GenerateLocales
	def self.generate

		I18n::JS::export
		File.open(Rails.root.join('app', 'javascript', 'i18n', 'locales', 'index.js'), 'w') do |file|
			file << "// DO NOT MODIFY THIS FILE. AUTOGENERATED\n"
			file << "const translations = {};\n\n"
			I18n::JS::translations.select{|k,v| Houdini.intl.available_locales.map(&:to_s).include?(k.to_s)}.each_key do |k|
				file << "translations['#{k}'] = require('./#{k}').default['#{k}'];\n"
			end

			file << "\nmodule.exports = translations"
		end

		File.open(Rails.root.join('app', 'javascript', 'i18n', 'locales', 'index.d.ts'), 'w') do |file|
			file << "// DO NOT MODIFY THIS FILE. AUTOGENERATED\n"
			file << "declare const translations: Record<string, any>;\n\n"
			file << "module.exports = translations"
		end
	end
end