// License: LGPL-3.0-or-later
// this will be generated by some route generator in future but for now, we'll handcode it.

export default {
	nonprofitsPayments: {
		path: (props: {id:string, pid?:string}):string => {
			const url = new URL(`/nonprofits/${props.id}/payments`, new URL(document.location.href));
			if(props.pid){
				url.searchParams.set('pid', props.pid);
			}

			return url.toString();
		},

		url: (props: {id:string, pid?:string}):string => {
			const url = new URL(`/nonprofits/${props.id}/payments`, new URL(document.location.href));
			if(props.pid){
				url.searchParams.set('pid', props.pid);
			}

			return url.toString();
		},

	},
};