# License: LGPL-3.0-or-later
name: Dependent Issues

on:
  issues:
    types:
      - opened
      - edited
      - reopened
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      # Makes sure we always add status check for PRs. Useful only if
      # this action is required to pass before merging. Can be removed
      # otherwise.
      - synchronize
  

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: write
      discussions: none
      packages: none
      pull-requests: write
      repository-projects: none
      security-events: none
      statuses: write
    steps:
      - uses: z0al/dependent-issues@v1.5.1
        env:
          # (Required) The token to use to make API calls to GitHub.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # (Optional) The token to use to make API calls to GitHub for remote repos.
          GITHUB_READ_TOKEN: ${{ secrets.GITHUB_READ_TOKEN }}
        with:
          # (Optional) The label to use to mark dependent issues
          label: dependent

          # (Optional) Enable checking for dependencies in issues.
          # Enable by setting the value to "on". Default "off"
          check_issues: off

          # (Optional) A comma-separated list of keywords. Default
          # "depends on, blocked by"
          keywords: depends on, blocked by