name: Deploy
run-name: Deploy - ${{ inputs.version_tag }}
on: 
 workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      mode:
        description: Mode to build
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
      version_tag:
        description: New Version To Create
        required: true
      commit_being_built:
        description: SHA of the original git version being built
        required: true
concurrency: 
  group: deploy--${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
      env:
        CUSTOM_RUBY_VERSION: ${{ matrix.ruby }}
        # normally, you'd want to use commitchange_development_legacy but that database hasn't been created
        BUILD_DATABASE_URL: postgres://admin:password@localhost/commitchange_development_legacy
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-22.04]
          node: [16]
          ruby: ['3.1.7']
          postgres: ['16']
        fail-fast: false
      steps:
        - name: 'Checkout our repo'
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.PAT_TO_RUN_AS_ERIC }}
              
        - name: Setup PostgreSQL with PostgreSQL extensions and unprivileged user
          uses: Daniel-Marynicz/postgresql-action@1.0.0
          with:
            postgres_db: commitchange_development_legacy
            postgres_image_tag: ${{ matrix.postgres }}-alpine
            postgres_user: admin
            postgres_password: password
        - uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node }}
            cache: 'yarn'
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: ${{ matrix.ruby }}
            bundler-cache: true

        - run: bin/setup
        - name: Run yarn build-all-${{ github.event.inputs.mode }}
          env:
            mode: ${{ github.event.inputs.mode }}
            ORG_NAME: commitchange
          run: yarn build-all-${mode}
        - name: "Push deploy"
          env:
            mode: ${{ github.event.inputs.mode }}
            NewVersionTag: ${{ github.event.inputs.version_tag }}
            commit_being_built: ${{github.event.inputs.commit_being_built}}
          run: |

            git add public -f 
            git config --global user.email "robot@commitchange.com"
            git config --global user.name "Robot"
            git commit -m "Deployed version of $commit_being_built"

            git tag $NewVersionTag-$mode-release-deploy
            git push origin $NewVersionTag-$mode-release-deploy

            git push origin HEAD:staging_deploy -f