# License: LGPL-3.0-or-later
# These jobs must pass even on builds where it shouldn't run
# We address this by making a placeholder action
name: Placeholder for Javascript build and test
on: [push, pull_request]
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.6.0]
    steps:
      - run: 'echo "Placeholder for lint"'
  jest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.6.0]
    steps:
      - run: 'echo "Placeholder for jest"'
  webpack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.6.0]
        ruby: [2.6.6]
    steps:
      - run: 'echo "Placeholder for webpack"'
    


    