# License: LGPL-3.0-or-later
# notice_js must pass even on builds where it shouldn't run
# We address this by making a placeholder action
name: Placeholder for NOTICE-js verification
on: ['push', 'pull_request']
jobs:
  notice_js:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Placeholder for notice_js"'