name: Download and cache any npm packages
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node:
        required: true
        type: string
jobs:
  npm-package-download:
    name: Download NPM packages
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-packages
        with:
          node: ${{ inputs.node }}
