# License: LGPL-3.0-or-later
# these jobs must always pass so we make placeholders
# We address this by making a placeholders for required jobs
name: Placeholders
on: ['push', 'pull_request']
jobs:
  notice_js:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Placeholder for notice_js"'
  notice_ruby:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Placeholder for notice_ruby"'
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.6.0]
    steps:
      - run: 'echo "Placeholder for lint"'
  jest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.6.0]
    steps:
      - run: 'echo "Placeholder for jest"'
  webpack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.6.0]
        ruby: [2.6.6]
    steps:
      - run: 'echo "Placeholder for webpack"'
  main_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.6.0]
        ruby: [2.6.6]
    steps:
      - run: 'echo "Placeholder for main_build"'