# License: LGPL-3.0-or-later
# these jobs must always pass so we make placeholders
# We address this by making a placeholders for required jobs
name: Placeholders
on: ['push', 'pull_request']
jobs:
  notice_ruby:
    runs-on: ubuntu-20.04
    steps:
      - run: 'echo "Placeholder for notice_ruby"'
  jest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [14.19.1]
    steps:
      - run: 'echo "Placeholder for jest"'
  webpack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [14.19.1]
    steps:
      - run: 'echo "Placeholder for webpack"'
  main_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [14.19.1]
        ruby: [2.7.6]
    steps:
      - run: 'echo "Placeholder for main_build"'
  rubocop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [14.19.1]
        ruby: [2.7.6]
    steps:
      - run: 'echo "Placeholder for rubocop"'
