# License: LGPL-3.0-or-later
# main_build must pass even on builds where it shouldn't run
# We address this by making a placeholder action
name: Placeholder for Ruby test and build
on: [push, pull_request]
jobs:
  main_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.6.0]
        ruby: [2.6.6]
    steps:
      - run: 'echo "Placeholder for main_build"'